version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      
      - PORT=8000
      - DATABASE_URL=postgresql://admin:adminpassword@postgres-db:5432/eve_db?schema=public
      - JWT_SECRET=my_super_secret_eve_key_123
    depends_on:
      - postgres-db
    restart: unless-stopped

  postgres-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=eve_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: